### PR TITLE
Account for preview server when configuring makeRequest url

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@tejohnso Please review, thanks

**Comment by ezequielc** [comment]
@stulees I am not sure if you tested it, but you should consider the test environment in this check too (http://rvaviewer-test.appspot.com/).

**Comment by stulees** [comment]
@ezequielc Good catch. I've revised in last commit, please review again. @tejohnso

**Comment by ezequielc** [comment]
@stulees 👍

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
