### PR TITLE
Add zoom functionality to preview

### PR DESCRIPTION
**Pull request by alex-deaconu**
Fix issue with missing placeholders

### CODE REVIEW

**Comment by alex-deaconu** [comment]
To ignore whitespace changes: https://github.com/Rise-Vision/viewer/pull/281/files?w=1

Staging: http://preview-zoom-ux-dot-rvaviewer-test.appspot.com/

@tejohnso @ezequielc @fjvallarino please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I couldn't take a look at the code yet, but functionality looks great!

**Comment by alex-deaconu** [comment]
@ezequielc thanks for validating. @fjvallarino @tejohnso wondering if you could review. Thanks!

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
