### PR TITLE
Made changes to integrate viewer with player

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Changed gitignore to keep viewer dist folder on github
Changed Viewer.html resource paths

@tejohnso @alex-deaconu please review. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi I can't say I'm a fan of the fact that the `dist` folder is now in the repo, but I would assume there are no alternatives we could consider to prevent that.

PR looks good 👍 . I would suggest coordinating with Support to perform a smoke test after the deployment; and I would advise against deploying this today, I would wait till next week.

Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu we may not need to include the dist folder to git if we implement the GCS approach where viewer would be distributed through GCS and player would download it from there. @tejohnso  FYI. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi interesting. Curious, why not download the files from rvashow2.appspot.com/dist/*?

**Comment by tejohnso** [comment]
@alex-deaconu What method would be used to get all the files from rvashow2.appspot.com/dist?  For GCS I think it's a simple `gsutil cp -r`

**Comment by alex-deaconu** [comment]
@tejohnso not sure if there's a way to retrieve all the folder contents. Thanks.

**Pull request closed without merging**
