### PR TITLE
Fix coverage report

### PR DESCRIPTION
**Pull request by settinghead**
- add readme badges
- coverage as artifact

### CODE REVIEW

**Comment by settinghead** [comment]
@alex-deaconu @ezequielc please review. Thanks!

**Comment by alex-deaconu** [comment]
@settinghead not seeing the report in the build (see rise-vision-apps for example: http://screencast.com/t/Ofs5sM2Qf) and the badge is not updated (https://github.com/Rise-Vision/viewer/tree/chore/coveralls). Thanks.

**Comment by settinghead** [comment]
@alex-deaconu please welcome coveralls bot!

**Comment by alex-deaconu** [comment]
@settinghead nice, thanks for fixing! 👍

**Pull request merged**
