### PR TITLE
ViewerDataController/ViewerDataInfo unit tests

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updated ViewerDataController tests to include showing RegistrationWidget
ViewerDataInfo tests

Refactored EntryPoint:
- Removed unneeded parameters used in ViewerDataInfo
- Removed `_initCommands` function and just created local variables for the callbacks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino @settinghead please review. Thanks!

**Comment by fjvallarino** [comment]
:+1:

**Comment by settinghead** [comment]
@alex-deaconu :+1:

**Comment by settinghead** [comment]
This PR is superseded by https://github.com/Rise-Vision/viewer/pull/164. Closing.

**Pull request closed without merging**
