### PR TITLE
Add rva gadget e2e test and update all screenshots

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino @ezequielc e2e tests for rva gadgets - please review

### CODE REVIEW

**Comment by ezequielc** [comment]
@tejohnso Could you add a link to the Presentation? I would like to review what to expect inside the black squares. Code looks good. Thanks

**Comment by tejohnso** [comment]
@ezequielc Here's [a link](https://apps.risevision.com/editor/workspace/02dc4f3a-fe6e-4137-8b56-aade141e51a4/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4).  All presentations, displays, and schedules relevant to the e2e tests start with `viewer-e2e`

**Comment by alex-deaconu** [comment]
@tejohnso @ezequielc  wondering if we should use a separate Company to store these assets, just to make sure nobody overwrites them by mistake. Thoughts? Thanks.

**Comment by ezequielc** [comment]
@tejohnso Looks good 👍  I liked @alex-deaconu's suggestion. Cheers!

**Comment by tejohnso** [comment]
@alex-deaconu Will do on the next PR.  @ezequielc FYI

**Pull request merged**
