### PR TITLE
Ping V3 watchdog

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@tejohnso @alex-deaconu @fjvallarino ready for review.

This goes along with https://github.com/Rise-Vision/rise-launcher-electron/pull/450 and pings the new watchdog alongside the existing one.

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by alex-deaconu** [comment]
@tejohnso agreed. Thanks.

**Comment by fjvallarino** [comment]
:+1:

**Comment by tejohnso** [comment]
@fjvallarino  @alex-deaconu see latest commit using existing postToPlayer()

**Comment by alex-deaconu** [comment]
@tejohnso 👍

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
