### PR TITLE
handle case where item.recurrenceDaysOfWeek is undefined

### PR DESCRIPTION
**Pull request by settinghead**

### CODE REVIEW

**Comment by settinghead** [comment]
@ezequielc @rodrigopavezi please review here: 
https://github.com/Rise-Vision/viewer/pull/170/files?w=0

**Comment by tejohnso** [comment]
@settinghead a few suggestions:
 - Whitespace corrections in a separate commit
 - Use str.includes() rather than str.indexOf() !== -1
 - Replace the seven line conditional with a function call

**Comment by settinghead** [comment]
@tejohnso 

- I turned off auto-linting feature in my editor and decided to do all the linting fixes at another time. It's simply distracting for the reviewers.
- I tried `str.include()` but failed some unit tests because PhantomJS doesn't seem to support it. So I had to stick with `str.indexOf() !== -1`
- Created a new function to check recurrence day conditions per your suggestion.

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
