### PR TITLE
Remove deprecated document.write when setting viewport tag

### PR DESCRIPTION
**Pull request by andrecardoso**
## Description
Remove `document.write` call in Viewer.html file.

## Motivation and Context
`document.write` is deprecated, use `appendChild` instead

## How Has This Been Tested?
Tested locally

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by andrecardoso** [comment]
[(2) Remove document.write from Viewer.html](https://trello.com/c/qYLVLcxm/368-2-remove-documentwrite-from-viewerhtml)

**Comment by alex-deaconu** [comment]
@andrecardoso can you please provide a staging link for this change by using either feature/fix/chore prefix for your branch name as per:
https://github.com/Rise-Vision/viewer/blob/master/.circleci/config.yml#L123.

Thanks.

**Comment by andrecardoso** [comment]
@alex-deaconu sure, I'll open a new PR. Thanks.

**Comment by alex-deaconu** [comment]
@andrecardoso thanks and sorry for the inconvenience I'd just like to test to ensure the functionality works as expected. Thanks.

**Comment by andrecardoso** [comment]
@alex-deaconu no problem, makes total sense. Thanks for testing it.

**Pull request closed without merging**
