### PR TITLE
Fix visibility variable name

### PR DESCRIPTION
**Pull request by alex-deaconu**
Add use case for empty non visible Placeholder

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Fix for #176 

@Rise-Vision/apps please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc @tejohnso @fjvallarino @settinghead not sure if the `@Rise-Vision/apps` works as I had expected it, so you may not have got notifications for this.

Wondering if one of you can review. Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu sorry, I received the notification last night but forgot to review it in the morning.

:+1:

**Comment by alex-deaconu** [comment]
@fjvallarino no worries, thanks!

**Pull request merged**
