### PR TITLE
Update Viewer.html

### PR DESCRIPTION
**Pull request by woneal1983**
I want to test this change out on a test server. This is to help me figure out a viewport issue I'm having with a new web view I'm wanting to use on all my android apps. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@woneal1983 this is deployed for testing at http://1-06-039.rvaviewer-test.appspot.com/. Thanks.

**Comment by woneal1983** [comment]
It works. This can be deployed whenever. Just let me know. Thanks

**Comment by alex-deaconu** [comment]
@woneal1983 the latest commit is now deployed at http://1-06-039.rvaviewer-test.appspot.com/ for testing. Thanks.

**Comment by alex-deaconu** [comment]
@woneal1983 deployed at http://1-06-039.rvaviewer-test.appspot.com/. Thanks.

**Comment by woneal1983** [comment]
The testing went great and everything resulted exactly the way it should have. This can be deployed unless you need to test as well. Thanks Alex for doing this and letting me test. Once deployed i can start beta testing the app with chromium v43 as a library. Thanks

**Comment by alex-deaconu** [comment]
@woneal1983 I have a couple of things that I'd like to bring up with the PR before merging:
- we're removing the `viewport` variable which we introduced in a previous PR. Is this something your players are using? Is this something that you know anyone else may be using?
- I'd like to re-name the parameters that you're using for the width/height to something more specific, such that there are not conflicts or confusion with any other width/height parameters that we may want to introduce. I would suggest something like `viewportWidth` and `viewportHeight` or simply `vw` `vh`, I'll leave that choice to you. 

Also, once we've finalized the code, I will need to test all the options myself to make sure it works as expected. 

Thanks.

**Comment by woneal1983** [comment]
I did the changes in a new pull request. There will no viewport unless it sees my two parameters and the width/height is fixed. Hopefully this will do and take care of the concerns.

**Comment by alex-deaconu** [comment]
@woneal1983 apologies for the late reply. I have just returned from vacation. 

In terms of the PR, the latest version does not insert a <viewport> by default. It should.

Why not have something like this:
```
if(w & h){
  line1 = '<meta name="viewport" content="width=' + w +', height=' + h + '">'; 
else{
  line1 = '<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">';   
}
```
?

Thanks.

**Comment by woneal1983** [comment]
Oh for some reason i thought you wanted it out. Yea thats fine. Just put that on a test server and let me test first so i can make sure everything is working as it should.

**Comment by alex-deaconu** [comment]
@woneal1983 I was referring to the `viewport=false` url parameter you added a while back: https://github.com/Rise-Vision/viewer/blob/master/war/Viewer.html#L43. 

This PR removes that, so I was just curious if it was that still used by any of your players? Thanks.

**Comment by woneal1983** [comment]
Actually no its not. It was used on the old google tv before android tv came out but i never published it out to the masses. To be sure that i didn't need it i will test it out what you proposed and see what happens. :)

**Comment by woneal1983** [comment]
From my initial test using regular html it works. Could you put this on the testing server for one last test. Thanks

**Comment by alex-deaconu** [comment]
@woneal1983 I just did, new version is http://1-06-039.rvashow2.appspot.com/. Please note this is using the production server. Thanks.

**Comment by alex-deaconu** [comment]
@woneal1983 since I don't have access to your fork, I've created a new branch and PR with these changes: https://github.com/Rise-Vision/viewer/pull/47. Let's continue this conversation there. Thanks!

**Comment by alex-deaconu** [comment]
Deployed with #47

**Pull request closed without merging**
