### PR TITLE
Remove deprecated document.write when setting viewport tag

### PR DESCRIPTION
**Pull request by andrecardoso**
## Description
Remove `document.write` call in Viewer.html file.

## Motivation and Context
`document.write` is deprecated, use `appendChild` instead

## How Has This Been Tested?
Tested locally by opening [`http://remove-document-write-dot-rvaviewer-test.appspot.com/?viewport=true&vh=100&vw=200`]() and [`http://remove-document-write-dot-rvaviewer-test.appspot.com/?viewport=true`]() and verifying the tag is rendered as expected.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by andrecardoso** [comment]
@alex-deaconu I added the link and the test steps to the description. Please let me know if this test is enough, I'm not familiar with the viewerport usage here.

**Comment by alex-deaconu** [comment]
@andrecardoso I'm not very familiar with what and where `viewport` is used either. Re: validations I tested and everything is working correctly. Thanks for staging!

**Comment by andrecardoso** [comment]
[(2) Remove document.write from Viewer.html](https://trello.com/c/qYLVLcxm/368-2-remove-documentwrite-from-viewerhtml)

**Comment by andrecardoso** [comment]
[(2) Remove document.write from Viewer.html](https://trello.com/c/qYLVLcxm/368-2-remove-documentwrite-from-viewerhtml)

**Pull request merged**
